### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by mgeduld** [FahimF/sd-gui#15] opened 2022-10-03 16:46 UTC
Generating got too 100% done, but then the app crashed with this error message:

`Traceback (most recent call last):

  File "/Users/<USER>/code/sd-gui/ui/base_tab.py", line 32, in generate
    image.save(self.parent.file_name)

  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/PIL/Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")

FileNotFoundError: [Errno 2] No such file or directory: 'output/sample_2022_10_03_12_41_34.png'

Abort trap: 6

(ml) glgpcadmins-MacBook-Pro:sd-gui $ /opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`

**Comment by FahimF** [comment] 2022-10-03 23:43
Sorry, it looks as if the installer script was missing that step but it was there in the manual instructions. Now fixed but the installer has issues. I need to re-work that one anyway. Will close this for now since the issue is resolved.

**Closed by FahimF** 2022-10-03 23:43 UTC
